os:
  - Visual Studio 2015

install:
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  - appveyor DownloadFile "https://raw.githubusercontent.com/swig/cccl/master/cccl"
  - appveyor DownloadFile "https://raw.githubusercontent.com/pandawing/generator-nm5/master/Execute-With-Retry.ps1"
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
  - ps: . .\Execute-With-Retry
  - ps: Execute-With-Retry { bash -c "pacman -Syu --noconfirm" }
  - ps: Execute-With-Retry { bash -c "pacman -S --noconfirm autoconf automake libtool gtk-doc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-fribidi mingw-w64-x86_64-freetype" }

build_script:
  - set CC=cccl
  - set CXX=cccl
  - set LD=cccl
  - set PKG_CONFIG_PATH=%PKG_CONFIG_PATH%:/mingw64/lib/pkgconfig
  - bash -c "mv cccl /usr/bin"
  - bash -c "exec 0</dev/null; ./autogen.sh"
  - bash -c "exec 0</dev/null; ./configure"
  - bash -c "exec 0</dev/null; make CFLAGS='/W4 /WX /wd4068'"

#test_script:
#  - bash -c "make check"

# disable automatic tests
test: off
